### PR TITLE
Fix to hyphenated taxonomies from uri

### PR DESCRIPTION
**Pull request by Alt-Ben**
Super tiny change to fix the hyphenated taxonomies in term uris.

### CODE REVIEW

**Comment by jasonvarga** [comment]
Can you explain the situation this is fixing? This isn't in the core so it might also be happening there.

**Comment by ryanmitchell** [comment]
Ok for now Ive opted for (1) as its the path of least friction for now.
Let me know if this works for your use case.

**Comment by ryanmitchell** [comment]
@Alt-Ben did you get a chance to review this fix?

**Comment by Alt-Ben** [comment]
Sorry! Just got around to checking - all looks good from my side! Thank you!

**Pull request merged**
