### PR TITLE
Fixed Variables origin not being serialized as string

### PR DESCRIPTION
**Pull request by FrittenKeeZ**
Ensure that Variables origin is properly serialized to locale string instead of a Variables object

### CODE REVIEW

**Comment by jasonvarga** [comment]
I just told you in the other issue that I'm working on it and to keep watching this.

**Comment by royduin** [comment]
Sorry! Just curious, maybe I can help

**Comment by ryanmitchell** [comment]
@jasonvarga Do you think we can close this one in favour of #168 ?

**Comment by jasonvarga** [comment]
Yup!

**Pull request closed without merging**
